name: Add label
on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./
        with:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          config: .github/label-configs.json