name: Add label
on:
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    name: Label issues and pull requests
    steps:
      - uses: actions/checkout@v2
      
      - uses: IvanFon/super-labeler-action@master
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"