name: Add label
on:
  pull_request:
    # types:
    #   - opened
    branches:
      - main
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const base_branch = context.payload.pull_request.base.ref;
            const head_branch = context.payload.pull_request.head.ref;
            
            if (head_branch.includes('feat') || head_branch.includes('feature')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["enhancement"]
              })
            } else if (head_branch.includes('fix') || head_branch.includes('hotfix') || head_branch.includes('bugfix')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["bug"]
              })
            } else if (base_branch.includes('prod')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["deploy"]
              })
            }