name: Add label
on:
  pull_request:
    # types:
    #   - opened
    branches:
      - main
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const head = context.payload.pull_request.head.ref;
            console.log(head)
            if (head.includes('feat') || head.includes('feature')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["enhancement"]
              })
            }