name: Project Management
on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize]
  
jobs:
  release-mastermind:
    name: Release Mastermind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Release Mastermind
        uses: Videndum/release-mastermind@0.0.0-alpha.7
        with:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          config: .github/config.json