name: PR Slack notification

on:
  pull_request:
    branches:
      - "main"

jobs:
  slack_notify:
    name: Send notification on Slack
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C04PUQFS8HE\",\"text\":\"Hello world\"}'